FROM python:3.8-slim

WORKDIR /app

COPY ./driver/requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./driver/fastAPI_driver.py /app/

EXPOSE 8000

CMD ["python", "fastAPI_driver.py"]